name: 构建Electron应用

# 添加权限配置到顶部
permissions:
  contents: write # 允许写入仓库内容（上传产物）
  actions: read # 允许读取Actions（下载其他工作流产物）

on:
  # 在Python服务构建工作流完成后触发
  workflow_run:
    workflows: ["构建Python服务"]
    types:
      - completed
    branches: [main, master]
  push:
    branches: [main, master]
    paths:
      - "src/**"
      - "package.json"
  # pull_request:
  #   branches: [main, master]
  #   paths:
  #     - "src/**"
  #     - "package.json"
  #     - "webpack.config.js"
  # 允许手动触发工作流
  workflow_dispatch:

jobs:
  # 构建Windows应用
  build-windows:
    runs-on: windows-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 安装pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.15.9

      - name: 设置Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.20.8
          cache: "pnpm"

      - name: 安装依赖
        run: pnpm install --frozen-lockfile

      - name: 构建Windows应用
        run: pnpm run electron:package

      - name: 上传Windows构建结果
        uses: actions/upload-artifact@v4
        with:
          name: windows-app
          path: release/*.exe
          retention-days: 7

  # 构建Mac Intel版本
  build-mac-intel:
    # runs-on: macos-12 # 使用Intel芯片的macOS运行器
    runs-on: macos-13 # 或 macos-12
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 打印芯片架构信息
        run: |
          # 检查CPU架构
          echo "CPU架构: $(uname -m)"
          echo "芯片: $(sysctl -n machdep.cpu.brand_string)"

      - name: 安装pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.15.9

      - name: 设置Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.20.8
          cache: "pnpm"

      - name: 安装依赖
        run: pnpm install --frozen-lockfile

      - name: 构建Mac Intel版本
        run: pnpm run electron:package

      - name: 上传Mac Intel构建结果
        uses: actions/upload-artifact@v4
        with:
          name: mac-intel-app
          path: release/*.dmg
          retention-days: 7

  # 构建Mac ARM版本
  build-mac-arm:
    runs-on: macos-14 # 使用ARM芯片的macOS运行器
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 打印芯片架构信息
        run: |
          # 检查CPU架构
          echo "CPU架构: $(uname -m)"
          echo "芯片: $(sysctl -n machdep.cpu.brand_string)"

      - name: 安装pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.15.9

      - name: 设置Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.20.8
          cache: "pnpm"

      - name: 安装依赖
        run: pnpm install --frozen-lockfile

      - name: 构建Mac ARM版本
        run: pnpm run electron:package

      - name: 上传Mac ARM构建结果
        uses: actions/upload-artifact@v4
        with:
          name: mac-arm-app
          path: release/*.dmg
          retention-days: 7
